[tool.poetry]
name = "service-lib"
version = "0.2.3"
description = ""
authors = ["Lawrence Naumov <prostolawr@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
sqlalchemy = "^2.0.37"
fastapi = "^0.115.6"
loguru = "^0.7.3"
pydantic-settings = "^2.7.1"
asyncpg = "^0.30.0"
alembic = "^1.14.0"

[tool.poetry.scripts]
init-db = "service_lib.base_db.create:run_init_db"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
